/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sportradar.sastre.football;

import org.junit.jupiter.api.Test;

class LiveWordCupTest {

    LiveWordCup liveWordCup = new LiveWordCup();
    @Test
    void shouldCreateMatchOnEmptyBoard() throws Exception {
        int count = liveWordCup.getSummary().size();
        liveWordCup.addMatch("Mexico","Canada");

        //assert sumary has one more country
    }

    @Test
    void shouldAddMatchOnExistingBoard() throws Exception {
        liveWordCup.addMatch("Spain","Brazil");
    }

    @Test
    void shouldFailCreateMatchWithWrongTeamName(){}

    @Test
    void shouldFailCreateAlreadyCreatedMatch(){}

    @Test
    void shouldFailCreateMatchWithWrongScore(){}

    @Test
    void shouldUpdateMatch(){}

    @Test
    void shouldFailUpdatingNonExistingMatch(){}

    @Test
    void shouldFailUpdatingMatchWithWrongScore(){}

    @Test
    void shouldFailUpdateMatchWithDecreasingScore(){}

    @Test
    void shouldUpdateMatchWithAnulatedScore(){}

    @Test
    void shouldFinishMatch(){}

    @Test
    void shouldFailFinishMatchWithWrongTeamName(){}

    @Test
    void shouldFailFinishMatchWithNonExistingMatch(){}

    @Test
    void shouldShowEmptyScoreBoard(){}

    @Test
    void shouldShowScoreSortedBoard(){}


}
