/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sportradar.sastre.football;

import com.sportradar.sastre.football.exception.WordCupException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LiveWordCupTest {

    LiveWordCup liveWordCup = new LiveWordCup();

    Logger logger = LogManager.getRootLogger();
    @Test
    void shouldCreateMatchOnEmptyBoard() throws Exception {
        int count = liveWordCup.getSummary().size();
        liveWordCup.addMatch("Mexico","Canada");
        logger.debug("Sumary {}", liveWordCup.getSummary());
        assertEquals(liveWordCup.getSummary().size(), count+1);
    }

    @Test
    void shouldAddMatchOnExistingBoard() throws Exception {
        liveWordCup.addMatch("Mexico","Canada");
        liveWordCup.addMatch("Spain","Brazil");
        logger.debug("Sumary {}", liveWordCup.getSummary());
    }

    @Test
    void shouldFailCreateMatchWithWrongTeamName() throws WordCupException{
        Exception exception = assertThrows(WordCupException.class, () -> {
            liveWordCup.addMatch("Mexico5","Canada");
        });
        assertTrue(exception.getMessage().contains("is not a valid classified country."));
    }

    @Test
    void shouldFailCreateAlreadyCreatedMatch() throws WordCupException{
        liveWordCup.addMatch("Mexico","Canada");
        Exception exception = assertThrows(WordCupException.class, () -> {
            liveWordCup.addMatch("Spain","Mexico");
        });
        assertEquals("MEXICO is already playing.", exception.getMessage());
    }

    @Test
    void shouldUpdateMatch() throws WordCupException {
        liveWordCup.addMatch("Mexico","Canada");
        liveWordCup.updateMatch("Mexico", 2,"Canada", 4);
        logger.debug("Sumary {}", liveWordCup.getSummary());
    }

    @Test
    void shouldFailUpdatingNonExistingMatch() throws WordCupException {
        liveWordCup.addMatch("Mexico","Canada");
        Exception exception = assertThrows(WordCupException.class, () -> {
            liveWordCup.updateMatch("Spain", 2,"Canada", 4);
        });
        assertEquals("Match not found.", exception.getMessage());
    }

    @Test
    void shouldFailUpdatingMatchWithNegativeScore() throws WordCupException {
        liveWordCup.addMatch("Mexico","Canada");
        Exception exception = assertThrows(WordCupException.class, () -> {
            liveWordCup.updateMatch("Mexico", -1,"Canada", 4);
        });
        assertEquals("Scores cannot be negative.", exception.getMessage());
    }

    @Test
    void shouldFailUpdateMatchWithDecreasingScore() throws WordCupException {
        liveWordCup.addMatch("Mexico","Canada");
        liveWordCup.updateMatch("Mexico", 2,"Canada", 4);
        Exception exception = assertThrows(WordCupException.class, () -> {
            liveWordCup.updateMatch("Mexico", 1,"Canada", 4);
        });
        assertEquals("Scores cannot decrease.", exception.getMessage());
    }
/**
    @Test
    void shouldUpdateMatchWithAnulatedScore(){}
*/
    @Test
    void shouldFinishMatch(){}

    @Test
    void shouldFailFinishMatchWithWrongTeamName(){}

    @Test
    void shouldFailFinishMatchWithNonExistingMatch(){}

    @Test
    void shouldShowEmptyScoreBoard(){

    }

    @Test
    void shouldShowScoreSortedBoard(){}


}
