package com.sportradar.sastre.football;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.sportradar.sastre.football.exception.WordCupException;
import com.sportradar.sastre.football.model.Country;
import com.sportradar.sastre.football.model.Match;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;

public class LiveWordCup {
    Logger logger = LogManager.getRootLogger();

    public List<Match> getSummary() {
        return summary;
    }

    private final List<Match> summary = new ArrayList<>();

    public void addMatch(String homeTeam, String awayTeam) throws WordCupException {
        logger.info("add new match between {} and {}", homeTeam, awayTeam);
        Country homeCountryTeam = validateAndReturnCountry(homeTeam);
        Country awayCountryTeam = validateAndReturnCountry(awayTeam);
        if (!homeCountryTeam.equals(awayCountryTeam)) {
            summary.add(new Match(homeCountryTeam, awayCountryTeam));
            logger.debug("The game between {} and {} starts now.", homeTeam, awayTeam);
        } else {
            WordCupException exception = new WordCupException("one country cannot play against itself");
            logger.info(exception);
            throw exception;
        }
    }

    public void updateMatch(String homeTeam, int homeScore, String awayTeam, int awayScore) throws WordCupException {
        logger.info("update Match to {} {} : {} {}", homeTeam, homeScore, awayTeam, awayScore);
        try {
            Match match = findMatch(homeTeam, awayTeam);
            validateScores(homeScore, awayScore, match);
            match.setHomeScore(homeScore);
            match.setAwayScore(awayScore);
        } catch (NoSuchElementException nsee) {
            WordCupException exception = new WordCupException("Match not found.");
            logger.info(exception);
            throw exception;
        }
    }

    public void finishMatch(String homeTeam, String awayTeam) throws WordCupException {
        logger.info("finish Match between {} and {}", homeTeam, awayTeam);
        try {
            summary.remove(findMatch(homeTeam, awayTeam));
        } catch (NoSuchElementException nsee) {
            WordCupException exception = new WordCupException("Match not found.");
            logger.info(exception);
            throw exception;
        }
    }

    public List<Match> getSortedSummary(){
        logger.info("get sorted Live Score");
        return summary.stream().sorted().toList();
    }

    private Country validateAndReturnCountry(String countryString) throws WordCupException {
        Country country = validateCountryStringAndReturnCountry(countryString);
        if (summary.stream().anyMatch(m -> m.getHomeTeam().equals(country) || m.getAwayTeam().equals(country))) {
            WordCupException exception = new WordCupException(country + " is already playing.");
            logger.info(exception);
            throw exception;
        }
        return country;
    }

    private Match findMatch(String homeTeam, String awayTeam) throws WordCupException {
        Country countryHomeTeam = validateCountryStringAndReturnCountry(homeTeam);
        Country countryAwayTeam = validateCountryStringAndReturnCountry(awayTeam);
        return summary.stream().filter(m -> m.getHomeTeam().equals(countryHomeTeam)
                && m.getAwayTeam().equals(countryAwayTeam)).findFirst().orElseThrow();
    }

    private Country validateCountryStringAndReturnCountry(String countryString) throws WordCupException {
        try {
            return Country.valueOf(countryString.toUpperCase());
        } catch (IllegalArgumentException e) {
            WordCupException exception = new WordCupException(countryString + " is not a valid classified country.");
            logger.info(exception);
            throw exception;
        }
    }

    private void validateScores(int homeScore, int awayScore, Match match) throws WordCupException {
        if (Integer.signum(homeScore) == -1 || Integer.signum(awayScore) == -1) {
            WordCupException exception = new WordCupException("Scores cannot be negative.");
            logger.info(exception);
            throw exception;
        }
        if (match.getHomeScore() > homeScore || match.getAwayScore() > awayScore) {
            WordCupException exception =  new WordCupException("Scores cannot decrease.");
            logger.info(exception);
            throw exception;
        }
    }
}
