package com.sportradar.sastre.football;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.sportradar.sastre.football.exception.WordCupException;
import com.sportradar.sastre.football.model.Country;
import com.sportradar.sastre.football.model.Match;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.ArrayList;
import java.util.List;

public class LiveWordCup {
    Logger logger = LogManager.getRootLogger();

    public List<Match> getSummary() {
        return summary;
    }

    private List<Match> summary = new ArrayList<>();
    public void addMatch(String homeTeam, String awayTeam) throws WordCupException {
        logger.debug("add new match between {} and {}", homeTeam, awayTeam);
        if (summary.isEmpty()){
            logger.debug("adding first match to the board");
        }
        logger.debug("sumary: {}", summary);
        Country homeCountryTeam = validateAndReturnCountry(homeTeam);
        Country awayCountryTeam = validateAndReturnCountry(awayTeam);
        validateCountryIsNotPlaying(homeCountryTeam);
        validateCountryIsNotPlaying(awayCountryTeam);
        summary.add(new Match(homeCountryTeam,awayCountryTeam));
        logger.debug("The game between {} and {} has already started", homeTeam, awayTeam);
    }

/**
    public void updateMatch(String homeTeam, int homeScore, String awayTeam, int awayScore) {
        validateTeamName();
        validateScore();
    }

     private void updateMatch(String homeTeam, int homeScore, String awayTeam, int awayScore, boolean fix) {
     validateTeamName();
     validateScore();
     }

    public void finishMatch(String homeTeam, String awayTeam) {
        validateTeamName();
        validateScore();
    }
    public List<T> getLiveScoreBoard() {
        validateTeamName();
        validateScore();
    }
    public List<T> getSummary() {
        validateTeamName();
        validateScore();
    }*/

    private void validateCountryIsNotPlaying(Country country) throws WordCupException{
        if (summary.stream().filter(m -> m.getHomeTeam().equals(country) || m.getAwayTeam().equals(country))
                .findFirst().isPresent()){
            throw new WordCupException(country + " is already playing.");
        }
    }

    private Country validateAndReturnCountry(String country) throws WordCupException{
        try{
            return Country.valueOf(country.toUpperCase());
        }catch (IllegalArgumentException e){
            throw new WordCupException(country +" is not a valid classified country.");
        }
    }
}
