/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sportradar.sastre.futbol;

import org.junit.jupiter.api.Test;

class LiveWordCupTest {

    @Test
    void shouldCreateMatchOnEmptyBoard(){}

    @Test
    void shouldAddMatchOnExistingBoard(){}

    @Test
    void shouldFailCreateMatchWithWrongTeamName(){}

    @Test
    void shouldFailCreateAlreadyCreatedMatch(){}

    @Test
    void shouldFailCreateMatchWithWrongScore(){}

    @Test
    void shouldUpdateMatch(){}

    @Test
    void shouldFailUpdatingNonExistingMatch(){}

    @Test
    void shouldFailUpdatingMatchWithWrongScore(){}

    @Test
    void shouldFailUpdateMatchWithDecreasingScore(){}

    @Test
    void shouldUpdateMatchWithAnulatedScore(){}

    @Test
    void shouldFinishMatch(){}

    @Test
    void shouldFailFinishMatchWithWrongTeamName(){}

    @Test
    void shouldFailFinishMatchWithNonExistingMatch(){}

    @Test
    void shouldShowEmptyScoreBoard(){}

    @Test
    void shouldShowScoreSortedBoard(){}


}
